[package]
name = "rusty-hacker"
version = "0.1.0"
authors = ["chck <shimekiri.today@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.9.*"
select = "0.4.*"